import {
  TESTING_ID_LOG_IN_DASHBOARD_BUTTON,
  TESTING_ID_LOG_IN_EMAIL_ADDRESS,
  TESTING_ID_LOG_IN_PASSWORD,
  TESTING_ID_LOG_IN_BUTTON,
  TESTING_ID_LOG_IN_USER_DROPDOWN,
  TESTING_ID_LOG_IN_USER_LOG_OUT,
} from "../../../utils/testingId";
